---
- hosts: localhost
  tasks:
    - name: 'Execute changes'
      shell: /usr/local/bin/tech-breakfix-cantboot-001 break
      args:
        executable: /bin/bash
    - name: 'Reboot...'
      shell: /usr/sbin/reboot
...

